genome_dir: /hps/nobackup/iqbal/lroberts/microbial_ecosystems/MAG_phylogeny_pipeline/species_phylogeny/test_genomes 
output_dir: /hps/nobackup/iqbal/lroberts/microbial_ecosystems/MAG_phylogeny_pipeline/species_phylogeny/test_output
