reference_genome: /hps/nobackup/iqbal/lroberts/microbial_ecosystems/MAG_phylogeny_pipeline/lineage_phylogeny/test_genomes/SAMD00055754.contigs.fa
genomes: /hps/nobackup/iqbal/lroberts/microbial_ecosystems/MAG_phylogeny_pipeline/lineage_phylogeny/test_genomes
output_dir: /hps/nobackup/iqbal/lroberts/microbial_ecosystems/MAG_phylogeny_pipeline/lineage_phylogeny/test_output
